[bar/ass]

enable-ipc = true
bottom = false
fixed-center = true
height = 30

background = #99000903
#background = #b3205e43

modules-left = i3
modules-center = d2
modules-right = xkeyboard memory network alsa

font-0 = JetBrainsMono:size=11:weight:semibold
font-1 = Agave Nerd Font Mono:size=18:style=bold;2

[module/cpu]
type = internal/cpu
interval = 3

format = <label>

label = %percentage-sum%
label-padding = 1
label-foreground = #ffffff

[module/i3]
type = internal/i3

ws-icon-0 = 1;1
ws-icon-1 = 2;2
ws-icon-2 = 3;3
ws-icon-3 = 4;4
ws-icon-4 = 5;5
ws-icon-5 = 6;6
ws-icon-6 = 7;7
ws-icon-7 = 8;8
ws-icon-8 = 9;9
ws-icon-9 = 0;10

label-focused = %icon%
label-focused-foreground = #ffffff
label-focused-padding = 2
label-focused-font = 0

label-unfocused = %icon%
label-unfocused-padding = 2 
label-unfocused-font = 0
label-unfocused-foreground = #b9b8cf

[module/memory]
type = internal/memory

interval = 1 
format = <label>
label = "%{F#ffffff}%{T2} %{T-}%{F#ffffff}RAM: %gb_used% / %gb_total% (%percentage_used%%)"
label-padding = 1

[module/wireless-network]
type = internal/network
interval = 3
interface = wlp0s20f3

format-connected = <label-connected>
format-disconnected = <label-disconnected>
format-packetloss = <animation-packetloss> <label-connected>
label-connected = 󰤨
label-disconnected = "no wifi :("
label-connected-padding = 1
label-disconnected-padding = 1
label-connected-foreground = #ffffff

[module/d1]
type = custom/script
exec = date +%A
format = " %{F#ffffff}<label> "
interval = 0.2

[module/d2]
type = custom/script
exec = date "+%d.%m.%y   %H:%M:%S"
format = "%{F#ffffff}<label>"
interval = 0.2
label-padding = 2

[module/alsa]
type = internal/alsa

; Soundcard to be used
; Usually in the format hw:# where # is the card number
; You can find the different card numbers in `/proc/asound/cards`
master-soundcard = default
speaker-soundcard = default
headphone-soundcard = default
master-mixer = Master
label-volume = %{T2} 󰕾 %{T-}%percentage%%
label-muted = %{T2}  %{T-}%percentage%%
label-volume-foreground = #ffffff
label-muted-foreground = #ffffff
label-volume-padding-right = 2
label-muted-padding-right = 2
iterval = 2

[module/network]
type = internal/network
interface = enp0s3
interface-type = wired
udspeed-minwidth = 5
accumulate-stats = true
unknown-as-up = true
speed-unit = ''
format-connected = <label-connected>
format-disconnected = <label-disconnected>
format-packetloss = <animation-packetloss> <label-connected>
label-connected = 󰤨
label-disconnected = "no internet :("
label-connected-padding = 1
label-disconnected-padding = 1
label-connected-foreground = #ffffff
#click-left = nm-connection-editor"

[module/xkeyboard]
type = internal/xkeyboard

; List of indicators to ignore
blacklist-0 = num lock
blacklist-1 = scroll lock
format = <label-layout>
label-layout-background = #ffffff
label-layout-foreground = #000
label-layout-padding = 1

